// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Tutorials: [{ type: "autogenerated", dirName: "Tutorials" }],
  Contribute: [{ type: "autogenerated", dirName: "Contribute" }],
}

module.exports = sidebars
